### ISSUE TITLE
[TF55]Populate teams by gender

### ISSUE THREAD

**Issue by raju2102** [phanijyothi11-tamu/team-formation#158]
Feature: Populate teams by gender
As a Professor,
So that I can ensure gender representation (female and other non-male genders) in teams,
I want to ensure that individuals from underrepresented gender groups are always teamed with others from similar backgrounds, so no team has only a single representative from these groups.

**Comment by ramya-gotika** [comment]
mplemented the balance_by_gender feature.
This implementation has been tested using RSpec, covering various scenarios to ensure robustness across different gender distributions and team compositions.
Cucumber scenarios haven't been written as it is dependent on the "Generate Teams" feature.

Implementation Details
The balance_by_gender feature follows these main steps:

Assign Female Students in Pairs: Female students are assigned first to ensure balanced gender representation across teams. Pairs of female students are added to teams with available spots, prioritizing skill level matching within the pairing constraints.
Handle Single Remaining Female: If there is a single unassigned female after pairing, she is assigned to a team with exactly two females and an available spot.
Assign 'Other' Gender Students: Remaining students who identify as ‘other’ are assigned to teams with exactly two females and an open spot.

Testing:

RSpec tests were conducted, simulating different student gender compositions and skill distributions to ensure the feature works as expected in diverse setups.
Inputs and outputs for each scenario are printed to provide transparency into the setup and outcome of each test, facilitating easier debugging and validation.
Note: Some tests are failing due to an existing bug unrelated to this implementation, affecting both RSpec and Cucumber results.
